<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Спасибо за регистрацию</title>
</head>
<body>
<h1>Подтверждение почты:</h1>
<img src="/images/confirm_image.png"/>
<h2>Ваш код подтверждения <span>${confirm_code}</span></h2>
</body>
</html>